### ISSUE TITLE
PSP/Vita support?

### ISSUE THREAD

**Issue by Webardo** [Eight-Mansions/linda-cubed-again#1]
Hello! Just wanted to know if this would be possible, unless you don't want to do it or can't do it, which both are fine.

Have a nice day!

**Comment by esperknight** [comment]
Hey,
I'm not sure to be honest.  It seems that the original ps1 game doesn't work as an boot either (I haven't tested it but have been told bt a few people).  But there is an official eboot version on the Sony store.  We're looking to see if somehow we can convert the official eboot into something we cna use to inject the files so maybe!  (No lick

**Comment by esperknight** [comment]
(Sigh... I shouldn't do this on mobile... I accidentally closed it.....)

**Comment by Webardo** [comment]
I see, thank you very much for answering so quickly!

Do know that PSN eboots have encryption, which can make things harder than necessary. You can use PSXtract to decrypt and decompress the eboot and obtain a clean original dump, and also check wether it's based on rev 0 or 1, but that's as far as it goes with current tools I think.

Anyway, I'm not too sure, but I believe the issue has to do with the way the game's executable is called from the BIOS, or something with a CD call.
Mrjaredbeta (mainly on POPS for PSP/Vita) and Ronnie Sahlberg (dev of pop-fe, a great eboot converter) over on GBATemp/PSXPlace know about this a lot better than me, so you should try contacting them too!

Ps. Don't worry about closing the issue like that, it's just a slip of the finger haha.

**Comment by Goatman13** [comment]
Issue can be fixed by appending 602112 (0x93000) '00' bytes at the end of bin file (HxD have option to insert bytes).

PSP is happy without modifying sector count at 0x9368-0x936C, but it needs to be updated for other emulators from `92 C1 04 00 00 04 C1 92` to `92 C2 04 00 00 04 C2 92` in current patch version. No idea how safe that is. Alternative solution will be moving exe to lower part of image like in original game, which i think is better solution. Still, PSP can be problematic with another file that will be close to end of disc.

I didn't debugged it properly because there is no way to do that on psp, also when i made it work i lost interest. :P It seems that bios request read that get past of the end of image. Adding up to 17 sectors is not enough, additional 256 sectors work, so it must be off by a lot. Other emulators are happy, so maybe it's just EBOOT conversion bug.

**Comment by esperknight** [comment]
Interesting.  That's definitely a huge disparity in sector count.  It may be due to what I'm using to rebuild the iso.  I'll see if I can fix that...

**Comment by esperknight** [comment]
@Goatman13 Thank you for the tip on how to fix this.  I ended up swapping to using lameguy64's psx imaging tools and that resolved the issue.  It definitely was the TOC being set larger than what was actually being used.

@Webardo Here's the latest patch that will fix this issue.  @mrnobodystudios tested it for me and it worked on this Vita so should work on PSP as well : https://github.com/Eight-Mansions/linda-cubed-again/releases/download/release-3/Linda_Cubed_Again-English-Patch-v0.95.3.zip
